# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk < Formula
  desc "A terminal task manager with TUI and CLI"
  homepage "https://github.com/stealth-patch/tsk"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stealth-patch/tsk/releases/download/v0.1.0/tsk_darwin_amd64.tar.gz"
    sha256 "37fe8652d8ec7703cd5709b056afdf604e4dfd97e8b59420d4878fea01f09fa9"

    def install
      bin.install "tsk"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stealth-patch/tsk/releases/download/v0.1.0/tsk_darwin_arm64.tar.gz"
    sha256 "1243a63de59f79218dd21264240014080c662dcb8d3a12b6e6d735c79e419077"

    def install
      bin.install "tsk"
    end
  end
end
