# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk < Formula
  desc "A terminal task manager with TUI and CLI"
  homepage "https://github.com/stealth-patch/tsk"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stealth-patch/tsk/releases/download/v0.1.0/tsk_darwin_amd64.tar.gz"
    sha256 "27505b14949e4594ab303c565639354a4c81189c3ee14d6b2ee541163e270a55"

    def install
      bin.install "tsk"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stealth-patch/tsk/releases/download/v0.1.0/tsk_darwin_arm64.tar.gz"
    sha256 "93654564cf9dff7d3a5bd32ef6e1b7c40eeee8dea737f1fae3b9596e2347f2ad"

    def install
      bin.install "tsk"
    end
  end
end
